repos:
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        entry: black hijos
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: black
        name: black
        entry: black hijos
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true
      
      - id: ruff
        name: ruff
        entry: ruff check --fix hijos
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true
      
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py311-plus
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

  
